name: Deploy oppfolgingshendelse topic to dev
on:
  push:
    branches:
      - main
    paths:
      - "kafka-topics/privat-oppfolgingshendelse-dev.yaml"
      - "kafka-topics/siste-oppfolgingsperiode-v2-dev.yaml"
  workflow_dispatch:

jobs:
  deploy-topics-dev:
    name: Deploy oppfolgingshendelse topic to dev
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Deploy kafka topics
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: kafka-topics/privat-oppfolgingshendelse-dev.yaml
          PRINT_PAYLOAD: true
      - name: Deploy kafka topic siste-oppfolgingsperiode-v2-dev
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: kafka-topics/siste-oppfolgingsperiode-v2-dev.yaml
          PRINT_PAYLOAD: true
